### ISSUE TITLE
Link not working in Terminator (Terminal)

### ISSUE THREAD

**Issue by pranshuchittora** [sindresorhus/ink-link#10]
Hi @sindresorhus , first of all, thank you for the awesome ink ecosystem.

I am trying to use ink-link in my project. Unfortunately, it's not working in the Terminator terminal (https://github.com/gnome-terminator/terminator) but working in the native ubuntu terminal.

### Terminator 
![Screenshot from 2021-02-03 03-34-18](https://user-images.githubusercontent.com/32242596/106669113-2ea3f780-65d1-11eb-8f1c-352a7bdcf180.png)

### Ubuntu Native Terminal
![Screenshot from 2021-02-03 03-34-45](https://user-images.githubusercontent.com/32242596/106669119-2fd52480-65d1-11eb-8329-0e708de8fe05.png)

Might not be the issue with ink-link, but not sure. Would be grateful if you can help in resolving this.

**Comment by sindresorhus** [comment]
Not all terminals are supported as pointed out by the readme. There's a link to a list of supported terminals there.

It seems like it detects that Terminator supports links, but does not. Otherwise, `ink-link` would have used a fallback. We use https://github.com/jamestalmage/supports-hyperlinks for the detection. You should open an issue there.

**Comment by pranshuchittora** [comment]
It's weird that other libs are able to render the link in the same terminal. 

![Screenshot from 2021-02-03 21-44-54](https://user-images.githubusercontent.com/32242596/106775469-28615a00-6669-11eb-97d4-a932e4a9b4c6.png)
